# Question 1

In [4]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [3]:
import numpy as np
lst=[]
lst1=[]
num=5
for i in range(0,num):
    list1=int(input())
    lst.append(list1)
print(lst)
for j in range(0,num):
    list2=int(input())
    lst1.append(list2)
print(lst1)
arr=np.array(lst)
print(arr) #converting list to numpy array
arr1=np.array(lst1)
print(arr1)
arr2=np.concatenate((arr,arr1)) #concatenating the numpy arrays
print(arr2)
print(np.sort(arr2)) #sorting the concatenated arrays

45
10
35
5
20
[45, 10, 35, 5, 20]
60
23
90
75
55
[60, 23, 90, 75, 55]
[45 10 35  5 20]
[60 23 90 75 55]
[45 10 35  5 20 60 23 90 75 55]
[ 5 10 20 23 35 45 55 60 75 90]


# Question 3

To find the dimensions of ndarray, ndim attribute is used. 
To find the size(number of elements) of NumPy array, shape attribute is used. 
To find the size(total number of elements) size attribute is used.

In [7]:
import numpy as np
a=np.arange(12).reshape((3,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
12


# Question 4

In [26]:
import numpy as np
a=np.arange(1,9)
print(a)
print(a.shape)
b=a[np.newaxis,:] 
print(b)
print(b.shape)
b=a[:,np.newaxis] 
print(b)
print(b.shape)
a=np.arange(1,9)
b=np.expand_dims(a,axis=0)
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4 5 6 7 8]]
(1, 8)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)
[[1 2 3 4 5 6 7 8]]
(1, 8)


# Question 5

vstack is used to combine 2 numpy arrays vertically. 

In [28]:
np_one=np.array([[1,2],[3,4]])
np_two=np.array([[5,6],[7,8]])
np.vstack((np_one,np_two))  

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

hstack is used to combine 2 numpy arrays horizontally.

In [29]:
np_one=np.array([[1,2],[3,4]])
np_two=np.array([[5,6],[7,8]])
np.hstack((np_one,np_two))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Question 6

We can get the count of unique values in a column using nunique()

In [12]:
import pandas as pd
data={
    'id':[1,2,3,1,2],
    'group':['abc','pqr','xyz','abc','mno'],
    'team':['team A','team B','team D', 'team A','team B']
}
df=pd.DataFrame(data)
print(df)
unique_values=df['team'].nunique()
print()
print("Unique values in team are:",unique_values)

   id group    team
0   1   abc  team A
1   2   pqr  team B
2   3   xyz  team D
3   1   abc  team A
4   2   mno  team B

Unique values in team are: 3


We can get the list of unique values in a column using unique()

In [6]:
df['group'].unique()

array(['abc', 'pqr', 'xyz', 'mno'], dtype=object)